name: gdgdevfest_emails
description: A utility that Generates access codes and qrcodes for confirmation mails of GDG Damanhour Devfest 2019.
version: 1.0.0
# homepage: https://www.example.com
author: ahmdaeyz <ahmedalarabe5@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'
executables:
  gdgdevfest_emails: gdgdevfest_emails
dependencies:
 qr: ^1.2.0
 csv: ^4.0.3
 image: any
 dio: ">=3.0.3 <6.0.0"
 args: ^1.5.2
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
